### ISSUE TITLE
URL Broken

### ISSUE THREAD

**Issue by duckie** [sevntu-checkstyle/checkstyle-samples#10]
Hi

Url : http://sevntu-checkstyle.github.io/sevntu.checkstyle/maven2

Seems broken, projects cant build anymore. I post it as an issue here because the samples contains that URL.

Thanks for your help

**Comment by romani** [comment]
url is not brocken, github does not allow to show content of folders but it works:

try http://sevntu-checkstyle.github.io/sevntu.checkstyle/maven2/com/github/sevntu/checkstyle/sevntu-checks/maven-metadata.xml

Prove from our CI build - https://travis-ci.org/sevntu-checkstyle/checkstyle-samples#L187

recheck you proxy repository managers - nexus or artifactory to be able to use third-party maven repos.

the same for update site for eclipse-cs, it does not shown in browser, but it works during installation process.

**Comment by duckie** [comment]
You were right, it was a proxy mismatched configuration. Sorry for the disturbance.
