### ISSUE TITLE
http://sevntu-checkstyle.github.io/sevntu.checkstyle/maven2  not found(404)

### ISSUE THREAD

**Issue by yourcaptain** [sevntu-checkstyle/checkstyle-samples#11]
http://sevntu-checkstyle.github.io/sevntu.checkstyle/maven2  not found(404)

**Comment by romani** [comment]
This is GitHub feature to not show directory structure. Maven not need this to work.

http://sevntu-checkstyle.github.io/sevntu.checkstyle/#distribution
